services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    env_file:
      - ./web/.env
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    expose:
      - "3001"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    expose:
      - "27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
